import {
    Button,
    Spinner,
    GroupBox,
    SpinBox,
    HorizontalBox,
    VerticalBox,
    GridBox, ComboBox, ProgressIndicator,
} from "std-widgets.slint";
import { MainScreen } from "screens/main.slint";
import { RetryOpenScreen } from "screens/retry-open.slint";

export component MainWindow inherits Window {
    in-out property <image> preview-image;
    in-out property <bool> failed_open_camera;
    callback retry_open_camera;
    callback quit;

    retry_screen := RetryOpenScreen {
        visible: failed_open_camera;
        retry => root.retry_open_camera();
        quit => root.quit();
    }
    MainScreen {
        visible: !retry_screen.visible;
    }
}
